In [1]:
import pandas as pd
import numpy as np

In [11]:
dataset = pd.read_csv('..//data//application_train.csv')
dataset = dataset.set_index('SK_ID_CURR')

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import cohen_kappa_score

from sklearn.utils import shuffle
from sklearn.model_selection import cross_val_predict

In [15]:
model = LogisticRegression()

In [77]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [56]:
features = imputed.drop(['TARGET'], axis=1)
labels = imputed['TARGET']

# Impute by median
features = dataset.fillna(dataset.median())

In [87]:
features

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,351000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,1129500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,135000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,297000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,513000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,454500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,1395000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,1530000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,913500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,405000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,652500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,135000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,67500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,697500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,679500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,247500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,387000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,157500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,454500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,427500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,927000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,247500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,702000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,675000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456225,1,Cash loans,M,N,Y,0,225000.000,297000.0,19975.5,297000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
456226,0,Cash loans,F,Y,Y,0,225000.000,500566.5,34969.5,472500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
456227,0,Cash loans,F,N,Y,0,99000.000,247275.0,16479.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
456228,0,Cash loans,F,Y,N,0,540000.000,545040.0,35617.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
456229,0,Revolving loans,F,N,Y,1,270000.000,180000.0,9000.0,180000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
456230,0,Cash loans,F,Y,Y,1,292500.000,355536.0,18283.5,270000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
456231,0,Cash loans,M,N,Y,0,117000.000,1071909.0,31473.0,936000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
456232,0,Cash loans,F,N,N,0,157500.000,135000.0,13351.5,135000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
456233,1,Cash loans,F,N,Y,0,225000.000,521280.0,23089.5,450000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
456234,0,Cash loans,M,N,Y,0,81000.000,135000.0,9148.5,135000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
456235,0,Cash loans,M,Y,Y,2,90000.000,1078200.0,31522.5,900000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
456236,0,Cash loans,M,Y,Y,0,585000.000,1575000.0,43443.0,1575000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
456237,0,Cash loans,F,N,Y,0,135000.000,946764.0,37678.5,765000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
456238,0,Cash loans,M,Y,N,1,270000.000,479700.0,46858.5,450000.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
456239,0,Cash loans,M,Y,N,0,180000.000,808650.0,23773.5,675000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
456240,0,Revolving loans,F,N,N,0,360000.000,337500.0,16875.0,337500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
456241,0,Cash loans,F,Y,Y,0,180000.000,270126.0,12028.5,193500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
456242,0,Cash loans,M,Y,Y,0,198000.000,1312110.0,52168.5,1125000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,225000.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,1138500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
456245,0,Cash loans,F,N,Y,3,81000.000,269550.0,11871.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
456246,0,Cash loans,F,N,Y,1,94500.000,225000.0,10620.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,247500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
456248,0,Cash loans,F,N,Y,0,153000.000,331920.0,16096.5,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
456249,0,Cash loans,F,N,Y,0,112500.000,225000.0,22050.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
456251,0,Cash loans,M,N,N,0,157500.000,254700.0,27558.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
456252,0,Cash loans,F,N,Y,0,72000.000,269550.0,12001.5,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,585000.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
456254,1,Cash loans,F,N,Y,0,171000.000,370107.0,20205.0,319500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,675000.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [88]:
le = LabelEncoder()
oh = OneHotEncoder()

le.fit(features[['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN']])
le_encoded = le.transform(features)

oh.fit(le_encoded)
oh.transform(le_encoded)

ValueError: bad input shape (307511, 4)

In [84]:
oh.fit(le_encoded)

ValueError: Expected 2D array, got 1D array instead:
array=[ 1.  0.  1. ...,  0.  0.  0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
features['CODE_GENDER']

In [ ]:
pred = cross_val_predict(model, features, labels, method='predict_proba')

In [59]:

pred = cross_val_predict(model, features[:1000], labels[:1000])

ValueError: could not convert string to float: 'Business Entity Type 3'

In [28]:
accuracy_score(pred, labels)

0.91927118054313506